import os

from dotenv import load_dotenv

load_dotenv(override=True)

TELEGRAM_TOKEN = os.getenv('TELEGRAM_TOKEN')
GOOGLE_SHEETS_CREDENTIALS_FILE = 'credentials.json'
GOOGLE_SHEETS_MAIN_DOC_ID = os.getenv('GOOGLE_SHEETS_MAIN_DOC_ID')
GOOGLE_SHEETS_USER_TEMPLATE_DOC_ID = os.getenv('GOOGLE_SHEETS_USER_TEMPLATE_DOC_ID')
GOOGLE_SHEETS_USER_LOG_FOLDER_ID = os.getenv('GOOGLE_SHEETS_USER_LOG_FOLDER_ID')
WEBHOOK_URL = os.getenv('WEBHOOK_URL')
SECRET_TOKEN = os.getenv('SECRET_TOKEN')
TELEGRAM_USER_ID = os.getenv('TELEGRAM_USER_ID')